# See DiskBinaryTreeSet.java for description

java_library(
    name = "disk_binary_tree_set",
    srcs = ["DiskBinaryTreeSet.java"],
)

java_binary(
    name = "disk_binary_tree_set_example",
    main_class = "pjrodriguez.dbts.DiskBinaryTreeSetExample",
    srcs = ["DiskBinaryTreeSetExample.java"],
    deps = [":disk_binary_tree_set"],
)